### ISSUE TITLE
Doesn't work with yii2 projects

### ISSUE THREAD

**Issue by machour** [icanhazstring/composer-unused#15]
**Describe the bug**
`composer unused` doesn't work for Yii2 projects, the following error messages are displayed:

```
 [ERROR] Could not load paths from root package to scan.
 [ERROR] No usages could be found. Aborting.
```

**Error dump**
Use `$ composer unused -vvv` to create an error dump and add it to the issue.

```
Reading ./composer.json
Loading config file /Users/machour/.composer/auth.json
Loading config file ./composer.json
Checked CA file /private/etc/ssl/cert.pem: valid
Executing command (/private/var/www/hidden/www.hidden.tn/www): git branch --no-color --no-abbrev -v
Reading /Users/machour/.composer/composer.json
Loading config file /Users/machour/.composer/auth.json
Loading config file /Users/machour/.composer/composer.json
Loading config file /Users/machour/.composer/auth.json
Reading /Users/machour/.composer/auth.json
Reading /private/var/www/hidden/www.hidden.tn/www/vendor/composer/installed.json
Reading /Users/machour/.composer/vendor/composer/installed.json
Loading plugin Foxy\Foxy
Reading ./composer.lock
Executing command (CWD): npm --version
Loading plugin yii\composer\Plugin
Loading plugin Icanhazstring\Composer\Unused\UnusedPlugin
Loading plugin SLLH\ComposerVersionsCheck\VersionsCheckPlugin
Running 1.8.0 (2018-12-03 10:31:16) with PHP 7.3.0 on Darwin / 18.2.0

Loading packages
----------------

 Loading 36 requirements
 36/36 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100% < 1 sec/< 1 sec 12.0 MiB

 ! [NOTE] Skipped 8 requirements. No package found or invalid constraint.

 * php
 * ext-gd
 * ext-json
 * ext-tidy
 * ext-pdo
 * ext-mbstring
 * ext-soap
 * yiisoft/yii2-redis

 ! [NOTE] Found 28 package(s) to be checked.


 [ERROR] Could not load paths from root package to scan.



 [ERROR] No usages could be found. Aborting.

````

**Additional information**

Reproduce steps:

```
composer create-project --prefer-dist --stability=dev yiisoft/yii2-app-basic basic
cd basic
composer unused
```

This has probably every thing to do with the way Yii2 handles autoloading (check basic/web/index.php):
```
require __DIR__ . '/../vendor/autoload.php';
require __DIR__ . '/../vendor/yiisoft/yii2/Yii.php';
```

**Comment by icanhazstring** [comment]
Hi @machour thanks for reporting. I will see what I can do. 🙂

**Comment by icanhazstring** [comment]
@machour can you check this with latest `dev-master` again?
I changed the way how the plugin parses your sources.

**Comment by machour** [comment]
It now works, thank you 👍 

Just a false-positive on [`foxy/foxy`](https://github.com/fxpio/foxy) which is considered unused although it's handling my assets for me.

**Comment by icanhazstring** [comment]
@machour can you give me a short example how `foxy/foxy` is integrated in your code?

**Comment by machour** [comment]
I'm not using it in my code at all. `foxy/foxy` is a plugin that automatically install npm packages for me when composer is done installing stuff, like assets-packagist, but without any PHP involved.

I think this kind of packages should be kept in a whitelist.

**Comment by icanhazstring** [comment]
@machour thanks for the clarification. I created #25 to address these kinds of packages.
The root problem here was solved, so we could close this one?

**Comment by machour** [comment]
Yes sir!
