### ISSUE TITLE
Detection of in-use packages that define no namespaces

### ISSUE THREAD

**Issue by AshleyPinner** [icanhazstring/composer-unused#24]
**Describe the bug**
Consider the simple case:
```JSON
{
    "require": {
        "paragonie/random_compat": "0.9.5",
    }
}
```

Random compat just defines the random_int/random_bytes functions in the global namespace for PHP5.x projects, so they can use the awesome random functions that 7.0 bought.

Since it has no namespaces, it's possibly impossible to detect if it's in use or not, yet `composer unused` will say:

```
 Unused packages
 * paragonie/random_compat ✗
```

I suggest that if a package has no namespaces, then it be put into a section that indicates that it's impossible to correctly identify if the package is in use or not via automated means.

This is also true of any package that defines only a static global class, such as `defuse/php-encryption` and `bitly/bitly-api-php` - again they don't actually have a namespace, so it's impossible to tell if they're in use by the namespaces being called.

**Comment by icanhazstring** [comment]
Hi @AshleyPinner thanks!

> I suggest that if a package has no namespaces, then it be put into a section that indicates that it's impossible to correctly identify if the package is in use or not via automated means.

That is a pretty nice idea. This could improve the way the user gets information about a package and if its an error of the `unused` plugin or a general lack of information inside a required package.

**Comment by AshleyPinner** [comment]
As an aside, this bug is as a result of the fixes in #11 - I was finally able to run the unused on my codebase, so thank you for fixing it 😃

**Comment by icanhazstring** [comment]
Good knews @AshleyPinner. I have pushed some changed into `master` which will show you if a package does not provide any namespace. They are listed as ignored.

If you wan't you can try it out already by using `dev-master` version.
Or just wait for `0.4.0` 😉

**Comment by icanhazstring** [comment]
Hi @AshleyPinner. Just tagged a new release `0.4.0`. Can you please confirm if this solves your problem 😉

**Comment by AshleyPinner** [comment]
``` Ignored packages
 ○ bitly/bitly-api-php (Package provides no namespace)
 ○ defuse/php-encryption (Package provides no namespace)
 ○ electrolinux/phpquery (Package provides no namespace)
 ○ paragonie/random_compat (Package provides no namespace)
```

Perfect.

**Comment by icanhazstring** [comment]
Thanks! 😄
