### ISSUE TITLE
"NonComposerComponentRegistration.php" directory does not exist

### ISSUE THREAD

**Issue by kkrieger85** [icanhazstring/composer-unused#3]
I tried to use this tool with fresh Magento2 Installation and got this result:

```
composer unused

Loading packages
----------------

 Loading 1 requirements
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ! [NOTE] Found 1 packages to be checked.



  [InvalidArgumentException]
  The "/Users/kkrieger/htdocs/kkrieger/magento-2.3/app/etc/NonComposerComponentRegistration.php" directory does not exist.
```

Do you need more data like composer.lock?

**Comment by icanhazstring** [comment]
Hi. Thanks for reaching out.

Would be nice to see  `composer.json` and `composer.lock`.

I'll try to see where the problem is exactly.

**Comment by kkrieger85** [comment]
[composer.json.txt](https://github.com/icanhazstring/composer-unused/files/3001792/composer.json.txt)
[composer.lock.txt](https://github.com/icanhazstring/composer-unused/files/3001793/composer.lock.txt)

**Comment by Nyholm** [comment]
I get the same error with AppKernel.php

I guess there is a minor thing with the classmap. 
```
    "autoload": {
      "psr-4": { "": "src/" },
      "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
    },
```

**Comment by Nyholm** [comment]
We should check the `$autoloadType` here: 
https://github.com/icanhazstring/composer-unused/blob/master/src/Command/UnusedCommand.php#L171-L187

**Comment by icanhazstring** [comment]
@nyholm good point. I think I need to merge definition for directories `psr-0` and `psr-0` with files from `classmap`. Thanks for figuring out!

**Comment by Pierstoval** [comment]
I've got the same problem too for the Kernel file 😄

**Comment by icanhazstring** [comment]
I just tagged a new release `0.1.1`.
Please give it a try if this solves your problems.

**Comment by kkrieger85** [comment]
@icanhazstring 

**Works for me** + Magento 2.3. now

```
Loading packages
----------------

 Loading 1 requirements
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ! [NOTE] Found 1 packages to be checked.

Scanning files...
-----------------

 663/663 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

Found 0 usued and 1 unused packages

Results
-------

 Used packages

 Unused packages
```

**Comment by kkrieger85** [comment]
BTW: In case of Magento 2.3. 

The only "unused package" is the meta package itself:

```
 Unused packages
 * magento/product-community-edition ✗
```

**Comment by icanhazstring** [comment]
I would then close this issue as solved.
If anything else happens, feel free to open a new one.

**Comment by Pierstoval** [comment]
Works for me too 😉 Perfectible, but the basics work!

**Comment by jonatanrdsantos** [comment]
Anyone landing here and facing an upgrade issue where `bin/magento` and  `NonComposerComponentRegistration.php` somehow get deleted just remove the packages:

`rm -rf vendor/magento/magento2-base vendor/magento/magento2-ee-base`
And run:

`composer install`
