### ISSUE TITLE
Exit code reflects unused packages exist

### ISSUE THREAD

**Issue by hgraca** [icanhazstring/composer-unused#30]
**Is your feature request related to a problem? Please describe.**
I want to put this tool in my CI pipeline, and for it to fail this step when there are unused packages.

**Describe the solution you'd like**
The solution is to make the `composer unused` exit with a code > 0 when there are unused packages detected.

**Comment by icanhazstring** [comment]
Hi @hgraca I think having this per default seems a bit strict. Are you fine, if we add a cli parameter `--strict` which will return an exit code > 0 if there are unused packages.

**Comment by bcremer** [comment]
A `--strict` CLI parameter is ambiguous. 
I would opt for `--with-exit-code`  if you like to have it opt-in or `--ignore-exit-code` if you decide to use it by default.

**Comment by icanhazstring** [comment]
Know that I think of it... you probably right @bcremer. The whole point of this tool is to provide a validation if you have unused packages. If you have, the tool should "fail" with an exit code.

Then I will probably take the later to ignore exit code if you want to.

**Comment by icanhazstring** [comment]
Since it is only merged into master, I just leave this open for now.
If you want, you can require `dev-master` to try it out if works for you.
