### ISSUE TITLE
Feature: Analyse code for `ext-` packages

### ISSUE THREAD

**Issue by icanhazstring** [icanhazstring/composer-unused#33]
**Is your feature request related to a problem? Please describe.**
Currently `ext-` packages from your `composer.json` will be ignored silently. This means, they won't show up in the result as `ignored`. In the future this could be improved to even scan your code for usages from these extensions.

**Describe the solution you'd like**
Maybe we can find a source how to map php extensions to there provided functions. Similar to what PHPStorm is doing with the Composer Plugin.

![image](https://user-images.githubusercontent.com/883543/55245048-acaf4e80-5242-11e9-9e1e-bb39a49ed12e.png)

**Additional information**
https://www.php.net/manual/de/function.get-extension-funcs.php

**Comment by icanhazstring** [comment]
Reference to #31

**Comment by hkdobrev** [comment]
FYI https://github.com/maglnet/ComposerRequireChecker (which kind of helps with the opposite of composer-unused) supports scanning for functions defined in extensions. Probably, some things ideas could be borrowed from there.

**Comment by icanhazstring** [comment]
Thanks @hkdobrev found the location.
Just leaving it here ;)

https://github.com/maglnet/ComposerRequireChecker/blob/master/src/ComposerRequireChecker/DefinedSymbolsLocator/LocateDefinedSymbolsFromExtensions.php

**Comment by marcelthole** [comment]
This looks interesting. I will try to add this feature with a new NodeParserStrategy. 
The `ReflectionExtension` looks good, because we can get the defined constants and classes provided by the Extension

**Comment by icanhazstring** [comment]
@marcelthole thanks! Go ahead. If you need any information don't hesitate to ask 👍
