### ISSUE TITLE
Feature: Add a manual to install the package locally

### ISSUE THREAD

**Issue by Finesse** [icanhazstring/composer-unused#34]
**Is your feature request related to a problem? Please describe.**

Saying local I mean installed through the project `package.json` file. Many people prefer local installation to global in order to:

- Not clog the system
- Have an ability to have different package versions for different projects
- Make their projects be installed using a single `composer install` command

**Describe the solution you'd like**

Add an instruction about how to install and use the «unused» package locally.

A common scenario is:

1. Install a package as a development dependency:

    ```bash
    composer require --dev icanhazstring/composer-unused
    ```
2. Add a script for it into the `composer.json` file:

    ```js
    {
        // ...
        "scripts": {
            "find-unused": "./vendor/bin/unused"
        }
    }
    ```
3. Run the composer script:

    ```bash
    composer run find-unused
    ```

Warning, this is a suggested manual and it may not work, I haven't checked it.

**Comment by icanhazstring** [comment]
Hi @Finesse thanks for reaching out. Should not be a big problem. I will see to it 🙂

**Comment by icanhazstring** [comment]
@Finesse since I don't need to change any code behavior. I simple updated the current `README.md` in `master`. The instruction is listed under  `Installation`.

Since composer will look for plugins in the global **and** local requirement, the command `composer-unused` stays the same.

**Comment by Finesse** [comment]
Cool, thank you 👍
