### ISSUE TITLE
Support type "symfony-bundle"

### ISSUE THREAD

**Issue by binarious** [icanhazstring/composer-unused#38]
**Is your feature request related to a problem? Please describe.**
In https://github.com/icanhazstring/composer-unused/issues/25 you ignored packages that are not of type `library`. This excludes Symfony bundles as well, most of them use the type `symfony-bundle` ([1](https://github.com/symfony/monolog-bundle/blob/005aefb1c4df246b07791188a65a0485fd6f4c5c/composer.json#L3), [2](https://github.com/symfony/twig-bundle/blob/f35cc0968f62d050ee66a580defca2283af5a74f/composer.json#L3), [3](https://github.com/symfony/maker-bundle/blob/186ffc80b8f363e04ea3c2ebf49e1263a84b4e39/composer.json#L5), [4](https://github.com/symfony/monolog-bundle/blob/005aefb1c4df246b07791188a65a0485fd6f4c5c/composer.json#L3), ...). 

**Describe the solution you'd like**
I'd like to be able to scan whether a Symfony bundle is used or not. [Symfony bundles are registered with their FQCN](https://symfony.com/doc/current/bundles/best_practices.html#installation-instructions) in `app/AppKernel.php` or in `config/bundles.php` (Symfony Flex). Therefore `symfony-bundle` should be supported.

**Comment by icanhazstring** [comment]
Hi @binarious. I only accepted the type `library` as the only bid type because it is the only one providing some kind of source with a namespace.

Then along comes symfony with a per spec invalid type. Well guess I will support it then as well 😉

Will see to it asap.

**Comment by icanhazstring** [comment]
@binarious fixed with `0.5.2`

Before:
![image](https://user-images.githubusercontent.com/883543/55954227-76b89400-5c5e-11e9-8396-423fa98dc906.png)

After:
![image](https://user-images.githubusercontent.com/883543/55954255-82a45600-5c5e-11e9-9b46-d5952f834052.png)

**Comment by binarious** [comment]
@icanhazstring ridiculously fast, thank you :+1:
I do get some false-positives though:
https://github.com/KnpLabs/KnpSnappyBundle
https://github.com/Elao/ErrorNotifierBundle

**Comment by icanhazstring** [comment]
Thanks. Will check those out.

**Comment by binarious** [comment]
Sure:
```php
<?php declare(strict_types = 1);

use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Config\Loader\LoaderInterface;

class AppKernel extends Kernel
{
    public function registerBundles()
    {
        $bundles = [
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
            
            new Elao\ErrorNotifierBundle\ElaoErrorNotifierBundle(),
            new Knp\Bundle\SnappyBundle\KnpSnappyBundle(),

            new AppBundle\AppBundle(),
        ];

        return $bundles;
    }
}
```

**Comment by icanhazstring** [comment]
Update:
Checked both out, working good so far.

What I used:
``` 
$ composer create-project symfony/skeleton
$ composer require elao/error-notifier-bundle
$ composer require knplabs/knp-snappy-bundle
$ composer unused
```

The are both required inside the `config/bundles.php`.

---

Let me check if there is a problem with your code if I use this.

**Comment by icanhazstring** [comment]
Ok Nevermind. Found the issue with `NewParseStrategy` this only works with FQNS.
Can you confirm this if you add a leading `\` in front of a package? (even if its not necessary)

`new \Knp\Bundle\SnappyBundle\KnpSnappyBundle()`

**Comment by binarious** [comment]
Yep, can confirm that.

**Comment by icanhazstring** [comment]
Alright. Will do another bugfix release then.
Thanks 👍

**Comment by binarious** [comment]
Great! Dankeschön 🙏

**Comment by icanhazstring** [comment]
And `0.5.3` tagged. Should work now 👍

**Comment by binarious** [comment]
Confirmed. Thanks again for your time and effort!

**Comment by icanhazstring** [comment]
yw 😄
