### ISSUE TITLE
Dump file is always created

### ISSUE THREAD

**Issue by binarious** [icanhazstring/composer-unused#41]
**Describe the bug**
Just running `composer unused` creates a `composer-unused-dump-*` file everytime.

**Additional information**
- composer unused: 0.5.3
- composer: 1.8.5
- php  7.3.4

**Comment by icanhazstring** [comment]
Should I tag another bugfix release or are there more issues coming? :D

**Comment by binarious** [comment]
I'm done for today :D. Thanks.

**Comment by icanhazstring** [comment]
`0.5.4` tagged. You can confirm the fix and close it if it works. Thanks 😃

**Comment by binarious** [comment]
Confirmed. :+1:
