### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by carusogabriel** [icanhazstring/composer-unused#48]
When typing `composer require --dev icanhazstring/composer-unused`, I'm getting an error and I can't install this package 😕 

```
Using version ^0.5.6 for icanhazstring/composer-unused
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for icanhazstring/composer-unused ^0.5.6 -> satisfiable by icanhazstring/composer-unused[0.5.6].
    - icanhazstring/composer-unused 0.5.6 requires zendframework/zend-servicemanager ^3.4 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by xuanquynh** [comment]
Could you post your composer.json?

**Comment by carusogabriel** [comment]
@xuanquynh Sorry, but is a private company package. What information do you need?

**Comment by xuanquynh** [comment]
I can install icanhazstring/composer-unused normally so I want to try with your composer.json.

Please try this command "composer search zendframework/zend-servicemanager" and tell me the output?

**Comment by carusogabriel** [comment]
> I can install icanhazstring/composer-unused normally so I want to try with your composer.json.

I see. So it is a local issue indeed. I'll try to figure out what is going on and share here.

> Please try this command "composer search zendframework/zend-servicemanager" and tell me the output?

```
zendframework/zend-servicemanager Factory-Driven Dependency Injection Container
zendframework/zend-servicemanager-di zend-di integration for zend-servicemanager
```

**Comment by xuanquynh** [comment]
The composer tells that "zendframework/zend-servicemanager ^3.4 -> no matching package found.". It means it could not find "zendframework/zend-servicemanager" package with version contraint ^3.4.

Could you try "composer require zendframework/zend-servicemanager:^3.4"?

**Comment by carusogabriel** [comment]
> Could you try "composer require zendframework/zend-servicemanager:^3.4"?

```
  [InvalidArgumentException]
  Could not find package zendframework/zend-servicemanager.

  Did you mean one of these?
      zendframework/zend-servicemanager
      zendframework/zend-servicemanager-di
```

**Comment by carusogabriel** [comment]
And if I copy the first `zendframework/zend-servicemanager` and try again, same error. btw, composer version: 

    Composer version 1.8.6 2019-06-11 15:03:05

**Comment by xuanquynh** [comment]
That is the problem. Your composer could not find "zendframework/zend-servicemanager" package. While it works normally in my computer.

**Comment by xuanquynh** [comment]
Do you change this composer configuration?

```bash
[repositories.packagist.org.type] composer
[repositories.packagist.org.url] https?://repo.packagist.org
[repositories.packagist.org.allow_ssl_downgrade] true
```

**Comment by carusogabriel** [comment]
Yeap:

```
    "repositories": [
        {"type": "composer", "url": "https://repo.packagist.com/COMPANY_NAME/"},
        {"packagist.org": false}
    ]
```

**Comment by icanhazstring** [comment]
Hi @carusogabriel this seems like a private packagist right?
Your company has to "add" the `zendframework/zend-servicemanager` into their private packagist repo.
If this isn't there, you will get the error your encounter right now.

**Comment by carusogabriel** [comment]
> Your company has to "add" the zendframework/zend-servicemanager into their private packagist repo.

It worked. Thanks for the help guys 🎉

**Comment by icanhazstring** [comment]
Thanks for changing the title @carusogabriel 👍
