### ISSUE TITLE
Feature: Check for used packages from autoload-dev

### ISSUE THREAD

**Issue by icanhazstring** [icanhazstring/composer-unused#49]
To ensure a proper production release ready build, dev requirements should not be included.

So ensure that no source code from dev requirements or the dev requirement tree is used without it to require as root requirement a new check should be implemented.

**Comment by icanhazstring** [comment]
Probably already covered by ComposerRequireChecker

**Comment by hkdobrev** [comment]
ComposerRequireChecker should check for that as it only crawls symbols defined in the `autoload` section of the dependencies. This specifically protects against soft dependencies which can very easily be installed as a soft dependency which is available by a dev tool in development and testing environments, but not on production.

**Comment by icanhazstring** [comment]
@hkdobrev thanks for clarification. Guess I will skip this feature, since it doesn't fit with the "unused packages" scope of this tool.

But again, thanks :)
