### ISSUE TITLE
PHAR file

### ISSUE THREAD

**Issue by stedekay** [icanhazstring/composer-unused#62]
I just want to ask if there are any plans on distributing a PHAR file for future releases. I think this tool would be a perfect match to be handled with PHIVE as its a dev dependency.

**Comment by icanhazstring** [comment]
Hi @stedekay. Yes there is. I will probably add a phar file to the next release as there are some issues using this tool as a root or global dependency which can't be resolved other that using a phar file.

See #61

Support an release should happen in the next couple of days.

**Comment by icanhazstring** [comment]
Hi @stedekay. The new release `0.7.0` and every further one, will have a `composer-unused.phar` which you can use.

https://github.com/icanhazstring/composer-unused/releases/latest

Closing this then, if everything is broken with it. Don't hesitate to open up a new issue.

**Comment by stedekay** [comment]
Perfect, will try it later. Do you also plan to add a gpg key so it is possible to add this phar via phive.xml?

**Comment by icanhazstring** [comment]
Yep, planning to do this during the next days.

**Comment by stedekay** [comment]
Great to hear! Thanks for your work.

**Comment by icanhazstring** [comment]
Signed release should be available when #68 is done.
