### ISSUE TITLE
{file}.php directory does not exist

### ISSUE THREAD

**Issue by ostrolucky** [icanhazstring/composer-unused#8]
This is similar issue as https://github.com/icanhazstring/composer-unused/issues/3 but this time for 
```json
"autoload": {
    "files": ["src/AppBundle/functions.php"]
},
```

configuration

**Comment by icanhazstring** [comment]
Hi @ostrolucky does this also occur with version `0.1.1`?

**Comment by ostrolucky** [comment]
It does not. Huh, I assumed composer installed newest version. I guess there was some cache dela.
