### ISSUE TITLE
Call to undefined method PhpParser\Node\Expr\PropertyFetch::isFullyQualified()

### ISSUE THREAD

**Issue by ostrolucky** [icanhazstring/composer-unused#9]
This happens with anonymous classes

```php
public function testSkipForNonExistentChatRooms(): void
{
    $transformer = new class ($this) implements DataTransformerInterface {
        /**
         * @var Assert
         */
        private $assert;

        public function __construct(Assert $assert)
        {
            $this->assert = $assert;
        }

        public function transform(array $data): array
        {
            $this->assert::assertEmpty($data);

            return $data;
        }
    };

    // rest of code
}
```

**Comment by icanhazstring** [comment]
Thanks for reporting!
Will get this cover asap.

**Comment by finagin** [comment]
https://github.com/icanhazstring/composer-unused/blob/5456ce395a4ffe59168ec7160422c734aead61af/src/Parser/Strategy/StaticParseStrategy.php#L22-L23

`$expression->class` may be `\PhpParser\Node\Name` or `\PhpParser\Node\Expr`
Only `\PhpParser\Node\Name` has `isFullyQualified` method

**Comment by icanhazstring** [comment]
I already changed the processing and testing of strategies.
I will upload an update soon :)

**Comment by icanhazstring** [comment]
@ostrolucky can you please install current `dev-master` and give it a try.

Since I reworked the parsing for the strategies I will publish a `0.2.0` after I added the debugging mode as well.

**Comment by ostrolucky** [comment]
dev-master works 👍

**Comment by icanhazstring** [comment]
Thanks. Tag should come up soon :)

**Comment by icanhazstring** [comment]
`0.2.0` tagged. So the fix is live :)
Thanks every1 ❤️
